# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf043b89c32bfb954065312b021e3bf2923071cba6c18d131a1305147ee458e43fa6521e0ed11aafed7c43272dbcd5cb4f601aafb88307fbf1600f6ea660c5f8

test:
  secret_key_base: 38600844f0f50e9f84bd4813cf19a9b08a541753d0decdb286550330f128f1731eda4b57cef4b4aa8796c9a2defe2032b2da0a6371e410e99ee18f42a8319cd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
